result = type('Hello')
name = 'John Doe'
result = name[3]
result = name[:]
result = name[1:]
result = name[:1]
result = name[-1]
result = name[::1]
result = name[::-1]
result = name[0:7:2]

result = "Hi there " + "Timmy"
result = "*" * 10
result = len("turple")
result = " I am alone".strip()
result = "On an island".strip('d')
result = "but life is good!".split()
result = "Help me".replace("me", "you")
result = "Need to make fire".startswith("Need")
result = "and cook rice".endswith("rice")
result = "bye bye".index('e')
result = "still there ?".upper()
result = "HELLO?!".lower()
result = "ok, I am done".capitalize()
result = "oh hi there".find('h')
result = "oh hi there".count('h')
name1 = 'John'
name2 = 'Jane'
result = f"Hello there {name1} and {name2}"
